### ISSUE TITLE
Impirium crashes on startup (FabricAPI included)

### ISSUE THREAD

**Issue by TheDoveNinja** [Bawnorton/Impirium#3]
When starting up, with no other mods than Impirium and FabricAPI, it crashes with an IllegalStateException of "No compatible attachment provider is available", with ByteBuddyAgent as the culprit. This occurs if the agent is called with a jre instead of jdk.
ByteBuddyAgent may need the jdk.attach module to be included.

**Comment by Bawnorton** [comment]
non-jdk runtimes are not supported, this is not a serious mod and I'm not gonna even try to support a runtime that doesn't support instrumentation

**Comment by TheDoveNinja** [comment]
Fair
